[package]
name = "vpm"
version = "0.1.0"
edition = "2021"
authors = ["MainKt <muhammad.saheed.iam@gmail.com>"]
description = "vpm-rs - An XBPS package management helper"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
